<table width="768" border="0" cellspacing="0" cellpadding="0" style="margin-bottom:8px;">
          <tr>
            <td height="37" class="title">{dede:field name='typename'/}<span class="more"><a href="{dede:field name='typeurl'/}">¸ü¶à..</a></span></td>
          </tr>
          <tr>
            <td valign="top" class="content">	
            
{dede:arclist      row='8'                 }		
<div id="case">
<div class="case_pic"><a href="[field:arcurl/]" target="_blank" style="height:113px; overflow:hidden;"><img src="[field:picname/]" width="160" height="120" style="border:0px solid #CCCCCC;" /></a></div><div class="case_tit"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
</div>
{/dede:arclist}


			</td>
          </tr>	
          <tr>
			<td height="5" align="center" valign="middle" class="page">&nbsp;</td>
    	  </tr>
        </table>