<?php
$z[0]=Array("flink","\r\n[field:link /]\r\n",294,372);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="32";
$z[0][4]['type']="text";
$z[1]=Array("channel","\r\n<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  | \r\n",414,583);
$z[1][4]['row']="4";
$z[1][4]['type']="son";
$z[1][4]['typeid']="11";
$z[2]=Array("global","",594,621);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",683,704);
$z[3][4]['name']="cfg_yw";
$z[4]=Array("global","",705,729);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",738,764);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",765,786);
$z[6][4]['name']="cfg_tj";
$z[7]=Array("global","",1032,1064);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1261,1281);
$z[8][4]['name']="cfg_q";
$z[9]=Array("global","",1496,1517);
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",1732,1754);
$z[10][4]['name']="cfg_qqq";
$z[11]=Array("global","",1869,1901);
$z[11][4]['name']="cfg_templets_skin";

?>