<?php
$z[0]=Array("global","",315,342);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",354,386);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",487,514);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",588,612);
$z[3][4]['name']="cfg_tbtxt";
$z[4]=Array("global","",670,697);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n",735,993);
$z[5][4]['row']="7";
$z[5][4]['type']="top";
$z[5][4]['currentstyle']="<li class='center'><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[6]=Array("type","\r\n<img src=\"/templets/moban/images/banner[field:id/].jpg\" width=\"980\" height=\"175\" alt=\"[field:typelink/]\" />\r\n",1042,1176);

?>