<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",323,355);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",427,462);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",537,560);
$z[4][4]['name']="seotitle";
$z[5]=Array("list","\r\n<li><b>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</b><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",601,750);
$z[5][4]['pagesize']="16";
$z[6]=Array("pagelist","",833,910);
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="3";
$z[7]=Array("include","",939,975);
$z[7][4]['filename']="right.htm";
$z[8]=Array("include","",985,1022);
$z[8][4]['filename']="footer.htm";

?>